name: Deployment
on:
  push:
    branches:
      - master
jobs:
    test:

        runs-on: ubuntu-latest
        steps:

            - name: Get code
              uses: actions/checkout@v4

            - name: Load and cache dependencies
              uses: ./.github/actions/cache_deps

            - name: Test code
              id: tests
              run: cd citizen-connect-fe && npm run test

            - name: Upload test report
              if: failure() && steps.tests.outcome == 'failure'
              uses: actions/upload-artifact@v4
              with:
                name: test-report
                path: test.json

    build:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v4

            - name: Installs dependencies
              uses: ./.github/actions/cache_deps

            - name: Create environment.prod.ts from Secret
              run: |
                mkdir -p citizen-connect-fe/src/environments
                echo "${{ secrets.ENV_PROD_TS }}" > citizen-connect-fe/src/environments/environment.prod.ts

            - name: Build the application
              run: cd citizen-connect-fe && npm run build

            - name: list contents of dist
              run: ls

            - name: Upload build artifacts
              uses: actions/upload-artifact@v4
              with:
                name: dist-files
                path: ./dist

    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v4
              
            - name: Download build artifacts
              uses: actions/download-artifact@v4
              with:
                name: dist-files
                path: ./dist/citizen-connect-fe/browser

            - name: Deploy application
              id: deploy
              uses: ./.github/actions/deploy
              env:
                AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
                AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
              with:
                bucketName: citizen-connect-fe
                distFiles: ./dist/citizen-connect-fe/browser

            - name: Get website URL
              run: echo "${{steps.deploy.outputs.URL}}"